### PR TITLE
bugfix: set CMAKE_INSTALL_DATAROOTDIR

### PR DESCRIPTION
**Pull request by drossberg**
via the GNUInstallDirs package

### CODE REVIEW

**Comment by drossberg** [comment]
This doesn't change the install directories but sets the CMAKE_INSTALL_DATAROOTDIR variable. With this, VYMBASEDIR gets the correct value.

**Comment by insilmaril** [comment]
Can the DATAROOTDIR then be overriden? On Linux for example I have currently this in the specfile:

%global cmake_options \\\
    -DCMAKE_INSTALL_DATAROOTDIR="share/vym" \\\
    -DCMAKE_INSTALL_MANDIR="%{_mandir}/man1" \\\
    -DCMAKE_INSTALL_DOCDIR="%{_defaultdocdir}/%{name}"

%cmake %{cmake_options}



(from [vym.spec](https://build.opensuse.org/package/view_file/home:insilmaril/vym/vym.spec?expand=1)) )

**Comment by drossberg** [comment]
Yes. I generated the CMake install script (cmake_install.cmake) once with GNUInstallDirs included and once without it and compared them. The two configurations generated identical install scripts. (The install script generated without the -DCMAKE_INSTALL_~ options has different destination directories.)

My actually goal is to improve the flag handling. But first, I have to make sure that VYMBASEDIR is set correctly. Unfortunately, CMAKE_INSTALL_DATAROOTDIR isn't set by default and with this, its value not visible in the configuration script.

**Comment by drossberg** [comment]
No opinion formed yet?

**Comment by insilmaril** [comment]
Looks reasonable, would like to test it with builds for all platforms, though and I am a bit busy the next couple of days

**Pull request merged**
